/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ed86937d-5b38-434e-a344-2479dbb24db1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_r5DtMCQ3t",
    "aws_user_pools_web_client_id": "1eafl59iqdiss67he7sm3p56a4",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "recycling-app-images-agawanea4c56b-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_r5DtMCQ3t",
        "userPoolWebClientId": "1eafl59iqdiss67he7sm3p56a4",
        "authenticationFlowType": "USER_PASSWORD_AUTH"
    },
    "Storage": {
        "AWSS3": {
            "bucket": "recycling-app-images-agawanea4c56b-dev",
            "region": "us-east-1"
        }
    },
    "API": {
        "REST": {
            "RecyclingAPI": {
                "endpoint": "https://axlnfr7ex4.execute-api.us-east-1.amazonaws.com/prod",
                "region": "us-east-1"
            }
        }
    }
};


export default awsmobile;
